# Generated by Django 4.1.7 on 2023-03-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='type',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HabitMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(auto_now=True)),
                ('habit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
            ],
        ),
    ]
