# Generated by Django 4.1.7 on 2023-03-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='habit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='habitmeta',
            name='habit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
    ]
