# Generated by Django 4.1.7 on 2023-03-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_frequency_habit_alter_habitmeta_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='habit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='habitmeta',
            name='habit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
    ]
