# Generated by Django 4.1.7 on 2023-03-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_frequency_habit_alter_habitmeta_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='recurrences',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='habitmeta',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
    ]
