# Generated by Django 4.1.7 on 2023-03-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habitmeta_date_completed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habitmeta',
            constraint=models.UniqueConstraint(fields=('habit', 'date_completed'), name='habit_date'),
        ),
    ]
