# Generated by Django 4.1.7 on 2023-03-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_recurrences_alter_habitmeta_habit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='recurrences',
        ),
    ]
