# Generated by Django 4.1.7 on 2023-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_habit_recurrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='type',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=255, null=True),
        ),
    ]
