# Generated by Django 4.1.7 on 2023-03-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmeta',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='habitmeta',
            name='summary',
        ),
        migrations.AddField(
            model_name='habitmeta',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
