# Generated by Django 4.1.7 on 2023-03-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_habitmeta_phase_remove_habitmeta_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_meta',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
