# Generated by Django 4.1.7 on 2023-03-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habit_habit_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='habit_meta',
        ),
        migrations.RemoveField(
            model_name='habitmeta',
            name='id',
        ),
        migrations.AlterField(
            model_name='habitmeta',
            name='habit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='habits.habit'),
        ),
    ]
