# Generated by Django 4.1.7 on 2023-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='streak',
        ),
        migrations.AddField(
            model_name='activity',
            name='phase',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=255, null=True),
        ),
    ]
