# Generated by Django 4.1.7 on 2023-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_activity_progress_remove_activity_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='phase',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=255, null=True),
        ),
    ]
