# Generated by Django 4.1.7 on 2023-03-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_activity_phase_activity_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='ActivityLog',
        ),
    ]
