# Generated by Django 4.1.7 on 2023-03-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_useractivitylog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tier',
        ),
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('master', 'master')], default='first', max_length=255, null=True),
        ),
    ]
