# Generated by Django 4.1.7 on 2023-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_useractivitylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
