# Generated by Django 4.1.7 on 2023-04-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_journal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, default='No Title', max_length=255),
        ),
    ]
